## Sprint 10 Project

In [15]:
#Import libraries and functions

import pandas as pd #Import pandas
import numpy as np #Import numpy
from IPython.display import Image, display, HTML #For image viewing and accessible formatting
import io #For formatting
from sklearn.model_selection import train_test_split #For model training
from sklearn.linear_model import LinearRegression #For model training
from numpy.random import RandomState #Import RandomState for bootstrapping
from sklearn.metrics import root_mean_squared_error

### i. Introduction

As of 2024, the global gold mining market was estimated at $260.86 billion, and is estimated to grow to $710.08 billion by 2033, according to Grand View Research (https://www.grandviewresearch.com/industry-analysis/gold-mining-market-report).

In [16]:
mining_url = "https://raw.githubusercontent.com/DHE42/sprint_10_repository/main/image_4.png"
display(Image(url=mining_url))

The industry relies on a two part refinement process composed of **flotation** and **purification**. During flotation, a substance called **flotation pulp** containing **reagent additions** is introduced into the **rougher feed**, or raw gold ore, to separate **concentrate** from **tails**. Concentrate is the ore in various stages of purification, and tails are residues from the refinement process that contain a low amount of valuable metals. The goal within the overall refinement process is to transform the rougher feed into a **final Au (gold) concentrate** that will have the highest possible amount of gold, and to produce **rougher tails** that have the lowest possible amount of valuable metals in them, as tails are discarded at the end of the refinement process.

In [17]:
refinement_url = "https://raw.githubusercontent.com/DHE42/sprint_10_repository/main/Image%206.png"
display(Image(url=refinement_url))

The goal of refinement in the gold industry is to maximize market product and minimize waste at every step. Data scientists are useful for this since they can use sound mathematical computing to predict recovery rates. **Recovery rates** are the percentage of gold successfully extracted from rougher feed at flotation to products produced through purification into the final Au concentrate and tails. Data scientists enable companies to sell their refined gold products at the highest possible market value by successfully predicting recovery rates to optimize extraction efficiency and maximize profitability.

In [18]:
profitability_url = "https://raw.githubusercontent.com/DHE42/sprint_10_repository/main/maximum_profitability.png"
display(Image(url=profitability_url))

### 1. Prepare the Data

#### 1.1 Open the files and look into the data.

In [ ]:
#Read and name CSVs

    #List URLs
full_df_url = "https://raw.githubusercontent.com/DHE42/sprint_10_repository/main/gold_recovery_full.csv"
train_df_url = "https://raw.githubusercontent.com/DHE42/sprint_10_repository/main/gold_recovery_train.csv"
test_df_url = "https://raw.githubusercontent.com/DHE42/sprint_10_repository/main/gold_recovery_test.csv"


full_df = pd.read_csv(full_df_url)
train_df = pd.read_csv(train_df_url)
test_df = pd.read_csv(test_df_url)

#Print head, description, and info for DFs

def display_dataframe_info(dataframes_dict):
    """
    Display head, description, and information for multiple dataframes
    
    Parameters:
    dataframes_dict (dict): Dictionary with dataframe names as keys and dataframes as values
    """
    
    # Display heads
    display(HTML(f"<h1>DataFrame Heads</h1>"))
    
    for name, df in dataframes_dict.items():
        display(HTML(f"<h2>{name} head</h2>"))
        print()
        display(df.head())
        print()
    
    # Display descriptions
    display(HTML(f"<h1>DataFrame Descriptions</h1>"))
    
    for name, df in dataframes_dict.items():
        display(HTML(f"<h2>{name} description</h2>"))
        print()
        display(df.describe())
        print()
    
    # Display info (now properly inside the function)
    display(HTML(f"<h1>DataFrame Info</h1>"))
    
    for name, df in dataframes_dict.items():
        display(HTML(f"<h2>{name} info<h2>"))
        print()
        display(df.info())
        print()

# Create a dictionary of your dataframes
dataframes = {
    'full_df': full_df,
    'train_df': train_df, 
    'test_df': test_df
}

# Call the function
display_dataframe_info(dataframes)

full_df head

,date,final.output.concentrate_ag,final.output.concentrate_pb,final.output.concentrate_sol,final.output.concentrate_au,final.output.recovery,final.output.tail_ag,final.output.tail_pb,final.output.tail_sol,final.output.tail_au,...,secondary_cleaner.state.floatbank4_a_air,secondary_cleaner.state.floatbank4_a_level,secondary_cleaner.state.floatbank4_b_air,secondary_cleaner.state.floatbank4_b_level,secondary_cleaner.state.floatbank5_a_air,secondary_cleaner.state.floatbank5_a_level,secondary_cleaner.state.floatbank5_b_air,secondary_cleaner.state.floatbank5_b_level,secondary_cleaner.state.floatbank6_a_air,secondary_cleaner.state.floatbank6_a_level
0,2016-01-15 00:00:00,6.055403,9.889648,5.507324,42.192020,70.541216,10.411962,0.895447,16.904297,2.143149,...,14.016835,-502.488007,12.099931,-504.715942,9.925633,-498.310211,8.079666,-500.470978,14.151341,-605.841980
1,2016-01-15 01:00:00,6.029369,9.968944,5.257781,42.701629,69.266198,10.462676,0.927452,16.634514,2.224930,...,13.992281,-505.503262,11.950531,-501.331529,10.039245,-500.169983,7.984757,-500.582168,13.998353,-599.787184
2,2016-01-15 02:00:00,6.055926,10.213995,5.383759,42.657501,68.116445,10.507046,0.953716,16.208849,2.257889,...,14.015015,-502.520901,11.912783,-501.133383,10.070913,-500.129135,8.013877,-500.517572,14.028663,-601.427363
3,2016-01-15 03:00:00,6.047977,9.977019,4.858634,42.689819,68.347543,10.422762,0.883763,16.532835,2.146849,...,14.036510,-500.857308,11.999550,-501.193686,9.970366,-499.201640,7.977324,-500.255908,14.005551,-599.996129
4,2016-01-15 04:00:00,6.148599,10.142511,4.939416,42.774141,66.927016,10.360302,0.792826,16.525686,2.055292,...,14.027298,-499.838632,11.953070,-501.053894,9.925709,-501.686727,7.894242,-500.356035,13.996647,-601.496691

train_df head
train_df head

,date,final.output.concentrate_ag,final.output.concentrate_pb,final.output.concentrate_sol,final.output.concentrate_au,final.output.recovery,final.output.tail_ag,final.output.tail_pb,final.output.tail_sol,final.output.tail_au,...,secondary_cleaner.state.floatbank4_a_air,secondary_cleaner.state.floatbank4_a_level,secondary_cleaner.state.floatbank4_b_air,secondary_cleaner.state.floatbank4_b_level,secondary_cleaner.state.floatbank5_a_air,secondary_cleaner.state.floatbank5_a_level,secondary_cleaner.state.floatbank5_b_air,secondary_cleaner.state.floatbank5_b_level,secondary_cleaner.state.floatbank6_a_air,secondary_cleaner.state.floatbank6_a_level
0,2016-01-15 00:00:00,6.055403,9.889648,5.507324,42.192020,70.541216,10.411962,0.895447,16.904297,2.143149,...,14.016835,-502.488007,12.099931,-504.715942,9.925633,-498.310211,8.079666,-500.470978,14.151341,-605.841980
1,2016-01-15 01:00:00,6.029369,9.968944,5.257781,42.701629,69.266198,10.462676,0.927452,16.634514,2.224930,...,13.992281,-505.503262,11.950531,-501.331529,10.039245,-500.169983,7.984757,-500.582168,13.998353,-599.787184
2,2016-01-15 02:00:00,6.055926,10.213995,5.383759,42.657501,68.116445,10.507046,0.953716,16.208849,2.257889,...,14.015015,-502.520901,11.912783,-501.133383,10.070913,-500.129135,8.013877,-500.517572,14.028663,-601.427363
3,2016-01-15 03:00:00,6.047977,9.977019,4.858634,42.689819,68.347543,10.422762,0.883763,16.532835,2.146849,...,14.036510,-500.857308,11.999550,-501.193686,9.970366,-499.201640,7.977324,-500.255908,14.005551,-599.996129
4,2016-01-15 04:00:00,6.148599,10.142511,4.939416,42.774141,66.927016,10.360302,0.792826,16.525686,2.055292,...,14.027298,-499.838632,11.953070,-501.053894,9.925709,-501.686727,7.894242,-500.356035,13.996647,-601.496691

test_df head
test_df head

,date,primary_cleaner.input.sulfate,primary_cleaner.input.depressant,primary_cleaner.input.feed_size,primary_cleaner.input.xanthate,primary_cleaner.state.floatbank8_a_air,primary_cleaner.state.floatbank8_a_level,primary_cleaner.state.floatbank8_b_air,primary_cleaner.state.floatbank8_b_level,primary_cleaner.state.floatbank8_c_air,...,secondary_cleaner.state.floatbank4_a_air,secondary_cleaner.state.floatbank4_a_level,secondary_cleaner.state.floatbank4_b_air,secondary_cleaner.state.floatbank4_b_level,secondary_cleaner.state.floatbank5_a_air,secondary_cleaner.state.floatbank5_a_level,secondary_cleaner.state.floatbank5_b_air,secondary_cleaner.state.floatbank5_b_level,secondary_cleaner.state.floatbank6_a_air,secondary_cleaner.state.floatbank6_a_level
0,2016-09-01 00:59:59,210.800909,14.993118,8.080000,1.005021,1398.981301,-500.225577,1399.144926,-499.919735,1400.102998,...,12.023554,-497.795834,8.016656,-501.289139,7.946562,-432.317850,4.872511,-500.037437,26.705889,-499.709414
1,2016-09-01 01:59:59,215.392455,14.987471,8.080000,0.990469,1398.777912,-500.057435,1398.055362,-499.778182,1396.151033,...,12.058140,-498.695773,8.130979,-499.634209,7.958270,-525.839648,4.878850,-500.162375,25.019940,-499.819438
2,2016-09-01 02:59:59,215.259946,12.884934,7.786667,0.996043,1398.493666,-500.868360,1398.860436,-499.764529,1398.075709,...,11.962366,-498.767484,8.096893,-500.827423,8.071056,-500.801673,4.905125,-499.828510,24.994862,-500.622559
3,2016-09-01 03:59:59,215.336236,12.006805,7.640000,0.863514,1399.618111,-498.863574,1397.440120,-499.211024,1400.129303,...,12.033091,-498.350935,8.074946,-499.474407,7.897085,-500.868509,4.931400,-499.963623,24.948919,-498.709987
4,2016-09-01 04:59:59,199.099327,10.682530,7.530000,0.805575,1401.268123,-500.808305,1398.128818,-499.504543,1402.172226,...,12.025367,-500.786497,8.054678,-500.397500,8.107890,-509.526725,4.957674,-500.360026,25.003331,-500.856333

full_df head

,final.output.concentrate_ag,final.output.concentrate_pb,final.output.concentrate_sol,final.output.concentrate_au,final.output.recovery,final.output.tail_ag,final.output.tail_pb,final.output.tail_sol,final.output.tail_au,primary_cleaner.input.sulfate,...,secondary_cleaner.state.floatbank4_a_air,secondary_cleaner.state.floatbank4_a_level,secondary_cleaner.state.floatbank4_b_air,secondary_cleaner.state.floatbank4_b_level,secondary_cleaner.state.floatbank5_a_air,secondary_cleaner.state.floatbank5_a_level,secondary_cleaner.state.floatbank5_b_air,secondary_cleaner.state.floatbank5_b_level,secondary_cleaner.state.floatbank6_a_air,secondary_cleaner.state.floatbank6_a_level
count,22627.000000,22629.000000,22331.000000,22630.000000,20753.000000,22633.000000,22516.000000,22445.000000,22635.000000,21107.000000,...,22571.000000,22587.000000,22608.000000,22607.000000,22615.000000,22615.000000,22615.000000,22616.000000,22597.000000,22615.000000
mean,4.781559,9.095308,8.640317,40.001172,67.447488,8.923690,2.488252,9.523632,2.827459,140.277672,...,18.205125,-499.878977,14.356474,-476.532613,14.883276,-503.323288,11.626743,-500.521502,17.976810,-519.361465
std,2.030128,3.230797,3.785035,13.398062,11.616034,3.517917,1.189407,4.079739,1.262834,49.919004,...,6.560700,80.273964,5.655791,93.822791,6.372811,72.925589,5.757449,78.956292,6.636203,75.477151
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000003,...,0.000000,-799.920713,0.000000,-800.836914,-0.423260,-799.741097,0.427084,-800.258209,-0.079426,-810.473526
25%,4.018525,8.750171,7.116799,42.383721,63.282393,7.684016,1.805376,8.143576,2.303108,110.177081,...,14.095940,-500.896232,10.882675,-500.309169,10.941299,-500.628697,8.037533,-500.167897,13.968418,-500.981671
50%,4.953729,9.914519,8.908792,44.653436,68.322258,9.484369,2.653001,10.212998,2.913794,141.330501,...,18.007326,-499.917108,14.947646,-499.612292,14.859117,-499.865158,10.989756,-499.951980,18.004215,-500.095463
75%,5.862593,10.929839,10.705824,46.111999,72.950836,11.084557,3.287790,11.860824,3.555077,174.049914,...,22.998194,-498.361545,17.977502,-400.224147,18.014914,-498.489381,14.001193,-499.492354,23.009704,-499.526388
max,16.001945,17.031899,19.615720,53.611374,100.000000,19.552149,6.086532,22.861749,9.789625,274.409626,...,60.000000,-127.692333,31.269706,-6.506986,63.116298,-244.483566,39.846228,-120.190931,54.876806,-29.093593

train_df head

,final.output.concentrate_ag,final.output.concentrate_pb,final.output.concentrate_sol,final.output.concentrate_au,final.output.recovery,final.output.tail_ag,final.output.tail_pb,final.output.tail_sol,final.output.tail_au,primary_cleaner.input.sulfate,...,secondary_cleaner.state.floatbank4_a_air,secondary_cleaner.state.floatbank4_a_level,secondary_cleaner.state.floatbank4_b_air,secondary_cleaner.state.floatbank4_b_level,secondary_cleaner.state.floatbank5_a_air,secondary_cleaner.state.floatbank5_a_level,secondary_cleaner.state.floatbank5_b_air,secondary_cleaner.state.floatbank5_b_level,secondary_cleaner.state.floatbank6_a_air,secondary_cleaner.state.floatbank6_a_level
count,16788.000000,16788.000000,16490.000000,16789.000000,15339.000000,16794.000000,16677.000000,16715.000000,16794.000000,15553.000000,...,16731.000000,16747.000000,16768.000000,16767.000000,16775.000000,16775.000000,16775.000000,16776.000000,16757.000000,16775.000000
mean,4.716907,9.113559,8.301123,39.467217,67.213166,8.757048,2.360327,9.303932,2.687512,129.479789,...,19.101874,-494.164481,14.778164,-476.600082,15.779488,-500.230146,12.377241,-498.956257,18.429208,-521.801826
std,2.096718,3.389495,3.825760,13.917227,11.960446,3.634103,1.215576,4.263208,1.272757,45.386931,...,6.883163,84.803334,5.999149,89.381172,6.834703,76.983542,6.219989,82.146207,6.958294,77.170888
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000003,...,0.000000,-799.920713,0.000000,-800.021781,-0.423260,-799.741097,0.427084,-800.258209,0.024270,-810.473526
25%,3.971262,8.825748,6.939185,42.055722,62.625685,7.610544,1.641604,7.870275,2.172953,103.064021,...,14.508299,-500.837689,10.741388,-500.269182,10.977713,-500.530594,8.925586,-500.147603,13.977626,-501.080595
50%,4.869346,10.065316,8.557228,44.498874,67.644601,9.220393,2.453690,10.021968,2.781132,131.783108,...,19.986958,-499.778379,14.943933,-499.593286,15.998340,-499.784231,11.092839,-499.933330,18.034960,-500.109898
75%,5.821176,11.054809,10.289741,45.976222,72.824595,10.971110,3.192404,11.648573,3.416936,159.539839,...,24.983961,-494.648754,20.023751,-400.137948,20.000701,-496.531781,15.979467,-498.418000,24.984992,-499.565540
max,16.001945,17.031899,18.124851,53.611374,100.000000,19.552149,6.086532,22.317730,9.789625,251.999948,...,60.000000,-127.692333,28.003828,-71.472472,63.116298,-275.073125,39.846228,-120.190931,54.876806,-39.784927

test_df head

,primary_cleaner.input.sulfate,primary_cleaner.input.depressant,primary_cleaner.input.feed_size,primary_cleaner.input.xanthate,primary_cleaner.state.floatbank8_a_air,primary_cleaner.state.floatbank8_a_level,primary_cleaner.state.floatbank8_b_air,primary_cleaner.state.floatbank8_b_level,primary_cleaner.state.floatbank8_c_air,primary_cleaner.state.floatbank8_c_level,...,secondary_cleaner.state.floatbank4_a_air,secondary_cleaner.state.floatbank4_a_level,secondary_cleaner.state.floatbank4_b_air,secondary_cleaner.state.floatbank4_b_level,secondary_cleaner.state.floatbank5_a_air,secondary_cleaner.state.floatbank5_a_level,secondary_cleaner.state.floatbank5_b_air,secondary_cleaner.state.floatbank5_b_level,secondary_cleaner.state.floatbank6_a_air,secondary_cleaner.state.floatbank6_a_level
count,5554.000000,5572.000000,5856.000000,5690.000000,5840.000000,5840.000000,5840.000000,5840.000000,5840.000000,5840.000000,...,5840.000000,5840.000000,5840.000000,5840.000000,5840.000000,5840.000000,5840.000000,5840.000000,5840.000000,5840.000000
mean,170.515243,8.482873,7.264651,1.321420,1481.990241,-509.057796,1486.908670,-511.743956,1468.495216,-509.741212,...,15.636031,-516.266074,13.145702,-476.338907,12.308967,-512.208126,9.470986,-505.017827,16.678722,-512.351694
std,49.608602,3.353105,0.611526,0.693246,310.453166,61.339256,313.224286,67.139074,309.980748,62.671873,...,4.660835,62.756748,4.304086,105.549424,3.762827,58.864651,3.312471,68.785898,5.404514,69.919839
min,0.000103,0.000031,5.650000,0.000003,0.000000,-799.773788,0.000000,-800.029078,0.000000,-799.995127,...,0.000000,-799.798523,0.000000,-800.836914,-0.223393,-799.661076,0.528083,-800.220337,-0.079426,-809.859706
25%,143.340022,6.411500,6.885625,0.888769,1497.190681,-500.455211,1497.150234,-500.936639,1437.050321,-501.300441,...,12.057838,-501.054741,11.880119,-500.419113,10.123459,-500.879383,7.991208,-500.223089,13.012422,-500.833821
50%,176.103893,8.023252,7.259333,1.183362,1554.659783,-499.997402,1553.268084,-500.066588,1546.160672,-500.079537,...,17.001867,-500.160145,14.952102,-499.644328,12.062877,-500.047621,9.980774,-500.001338,16.007242,-500.041085
75%,207.240761,10.017725,7.650000,1.763797,1601.681656,-499.575313,1601.784707,-499.323361,1600.785573,-499.009545,...,18.030985,-499.441529,15.940011,-401.523664,15.017881,-499.297033,11.992176,-499.722835,21.009076,-499.395621
max,274.409626,40.024582,15.500000,5.433169,2212.432090,-57.195404,1975.147923,-142.527229,1715.053773,-150.937035,...,30.051797,-401.565212,31.269706,-6.506986,25.258848,-244.483566,14.090194,-126.463446,26.705889,-29.093593

full_df info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22716 entries, 0 to 22715
Data columns (total 87 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   date                                                22716 non-null  object
 1   final.output.concentrate_ag                         22627 non-null  float64
 2   final.output.concentrate_pb                         22629 non-null  float64
 3   final.output.concentrate_sol                        22331 non-null  float64
 4   final.output.concentrate_au                         22630 non-null  float64
 5   final.output.recovery                               20753 non-null  float64
 6   final.output.tail_ag                                22633 non-null  float64
 7   final.output.tail_pb                                22516 non-null  float64
 8   final.output.tail_sol                               22445 non-null  float64
 9   final.output.tail_au                                22635 non-null  float64
 10  primary_cleaner.input.sulfate                       21107 non-null  float64
 11  primary_cleaner.input.depressant                    21170 non-null  float64
 12  primary_cleaner.input.feed_size                     22716 non-null  float64
 13  primary_cleaner.input.xanthate                      21565 non-null  float64
 14  primary_cleaner.output.concentrate_ag               22618 non-null  float64
 15  primary_cleaner.output.concentrate_pb               22268 non-null  float64
 16  primary_cleaner.output.concentrate_sol              21918 non-null  float64
 17  primary_cleaner.output.concentrate_au               22618 non-null  float64
 18  primary_cleaner.output.tail_ag                      22614 non-null  float64
 19  primary_cleaner.output.tail_pb                      22594 non-null  float64
 20  primary_cleaner.output.tail_sol                     22365 non-null  float64
 21  primary_cleaner.output.tail_au                      22617 non-null  float64
 22  primary_cleaner.state.floatbank8_a_air              22660 non-null  float64
 23  primary_cleaner.state.floatbank8_a_level            22667 non-null  float64
 24  primary_cleaner.state.floatbank8_b_air              22660 non-null  float64
 25  primary_cleaner.state.floatbank8_b_level            22673 non-null  float64
 26  primary_cleaner.state.floatbank8_c_air              22662 non-null  float64
 27  primary_cleaner.state.floatbank8_c_level            22673 non-null  float64
 28  primary_cleaner.state.floatbank8_d_air              22661 non-null  float64
 29  primary_cleaner.state.floatbank8_d_level            22673 non-null  float64
 30  rougher.calculation.sulfate_to_au_concentrate       22672 non-null  float64
 31  rougher.calculation.floatbank10_sulfate_to_au_feed  22672 non-null  float64
 32  rougher.calculation.floatbank11_sulfate_to_au_feed  22672 non-null  float64
 33  rougher.calculation.au_pb_ratio                     21089 non-null  float64
 34  rougher.input.feed_ag                               22618 non-null  float64
 35  rougher.input.feed_pb                               22472 non-null  float64
 36  rougher.input.feed_rate                             22163 non-null  float64
 37  rougher.input.feed_size                             22277 non-null  float64
 38  rougher.input.feed_sol                              22357 non-null  float64
 39  rougher.input.feed_au                               22617 non-null  float64
 40  rougher.input.floatbank10_sulfate                   21415 non-null  float64
 41  rougher.input.floatbank10_xanthate                  22247 non-null  float64
 42  rougher.input.floatbank11_sulfate                   22038 non-null  float64
 43  rougher.input.floatbank11_xanthate                  20459 non-null  float64
 44  rougher.output.concentrate_ag                       22618 non-null  float64
 45  rougher.output.concentrate_pb                       22618 non-null  float64
 46  rougher.output.concentrate_sol                      22526 non-null  float64
 47  rougher.output.concentrate_au                       22618 non-null  float64
 48  rougher.output.recovery                             19597 non-null  float64
 49  rougher.output.tail_ag                              19979 non-null  float64
 50  rougher.output.tail_pb                              22618 non-null  float64
 51  rougher.output.tail_sol                             19980 non-null  float64
 52  rougher.output.tail_au                              19980 non-null  float64
 53  rougher.state.floatbank10_a_air                     22646 non-null  float64
 54  rougher.state.floatbank10_a_level                   22647 non-null  float64
 55  rougher.state.floatbank10_b_air                     22646 non-null  float64
 56  rougher.state.floatbank10_b_level                   22647 non-null  float64
 57  rougher.state.floatbank10_c_air                     22646 non-null  float64
 58  rougher.state.floatbank10_c_level                   22654 non-null  float64
 59  rougher.state.floatbank10_d_air                     22641 non-null  float64
 60  rougher.state.floatbank10_d_level                   22649 non-null  float64
 61  rougher.state.floatbank10_e_air                     22096 non-null  float64
 62  rougher.state.floatbank10_e_level                   22649 non-null  float64
 63  rougher.state.floatbank10_f_air                     22641 non-null  float64
 64  rougher.state.floatbank10_f_level                   22642 non-null  float64
 65  secondary_cleaner.output.tail_ag                    22616 non-null  float64
 66  secondary_cleaner.output.tail_pb                    22600 non-null  float64
 67  secondary_cleaner.output.tail_sol                   20501 non-null  float64
 68  secondary_cleaner.output.tail_au                    22618 non-null  float64
 69  secondary_cleaner.state.floatbank2_a_air            22333 non-null  float64
 70  secondary_cleaner.state.floatbank2_a_level          22591 non-null  float64
 71  secondary_cleaner.state.floatbank2_b_air            22538 non-null  float64
 72  secondary_cleaner.state.floatbank2_b_level          22588 non-null  float64
 73  secondary_cleaner.state.floatbank3_a_air            22585 non-null  float64
 74  secondary_cleaner.state.floatbank3_a_level          22587 non-null  float64
 75  secondary_cleaner.state.floatbank3_b_air            22592 non-null  float64
 76  secondary_cleaner.state.floatbank3_b_level          22590 non-null  float64
 77  secondary_cleaner.state.floatbank4_a_air            22571 non-null  float64
 78  secondary_cleaner.state.floatbank4_a_level          22587 non-null  float64
 79  secondary_cleaner.state.floatbank4_b_air            22608 non-null  float64
 80  secondary_cleaner.state.floatbank4_b_level          22607 non-null  float64
 81  secondary_cleaner.state.floatbank5_a_air            22615 non-null  float64
 82  secondary_cleaner.state.floatbank5_a_level          22615 non-null  float64
 83  secondary_cleaner.state.floatbank5_b_air            22615 non-null  float64
 84  secondary_cleaner.state.floatbank5_b_level          22616 non-null  float64
 85  secondary_cleaner.state.floatbank6_a_air            22597 non-null  float64
 86  secondary_cleaner.state.floatbank6_a_level          22615 non-null  float64
dtypes: float64(86), object(1)
memory usage: 15.1+ MB

None

train_df info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16860 entries, 0 to 16859
Data columns (total 87 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   date                                                16860 non-null  object
 1   final.output.concentrate_ag                         16788 non-null  float64
 2   final.output.concentrate_pb                         16788 non-null  float64
 3   final.output.concentrate_sol                        16490 non-null  float64
 4   final.output.concentrate_au                         16789 non-null  float64
 5   final.output.recovery                               15339 non-null  float64
 6   final.output.tail_ag                                16794 non-null  float64
 7   final.output.tail_pb                                16677 non-null  float64
 8   final.output.tail_sol                               16715 non-null  float64
 9   final.output.tail_au                                16794 non-null  float64
 10  primary_cleaner.input.sulfate                       15553 non-null  float64
 11  primary_cleaner.input.depressant                    15598 non-null  float64
 12  primary_cleaner.input.feed_size                     16860 non-null  float64
 13  primary_cleaner.input.xanthate                      15875 non-null  float64
 14  primary_cleaner.output.concentrate_ag               16778 non-null  float64
 15  primary_cleaner.output.concentrate_pb               16502 non-null  float64
 16  primary_cleaner.output.concentrate_sol              16224 non-null  float64
 17  primary_cleaner.output.concentrate_au               16778 non-null  float64
 18  primary_cleaner.output.tail_ag                      16777 non-null  float64
 19  primary_cleaner.output.tail_pb                      16761 non-null  float64
 20  primary_cleaner.output.tail_sol                     16579 non-null  float64
 21  primary_cleaner.output.tail_au                      16777 non-null  float64
 22  primary_cleaner.state.floatbank8_a_air              16820 non-null  float64
 23  primary_cleaner.state.floatbank8_a_level            16827 non-null  float64
 24  primary_cleaner.state.floatbank8_b_air              16820 non-null  float64
 25  primary_cleaner.state.floatbank8_b_level            16833 non-null  float64
 26  primary_cleaner.state.floatbank8_c_air              16822 non-null  float64
 27  primary_cleaner.state.floatbank8_c_level            16833 non-null  float64
 28  primary_cleaner.state.floatbank8_d_air              16821 non-null  float64
 29  primary_cleaner.state.floatbank8_d_level            16833 non-null  float64
 30  rougher.calculation.sulfate_to_au_concentrate       16833 non-null  float64
 31  rougher.calculation.floatbank10_sulfate_to_au_feed  16833 non-null  float64
 32  rougher.calculation.floatbank11_sulfate_to_au_feed  16833 non-null  float64
 33  rougher.calculation.au_pb_ratio                     15618 non-null  float64
 34  rougher.input.feed_ag                               16778 non-null  float64
 35  rougher.input.feed_pb                               16632 non-null  float64
 36  rougher.input.feed_rate                             16347 non-null  float64
 37  rougher.input.feed_size                             16443 non-null  float64
 38  rougher.input.feed_sol                              16568 non-null  float64
 39  rougher.input.feed_au                               16777 non-null  float64
 40  rougher.input.floatbank10_sulfate                   15816 non-null  float64
 41  rougher.input.floatbank10_xanthate                  16514 non-null  float64
 42  rougher.input.floatbank11_sulfate                   16237 non-null  float64
 43  rougher.input.floatbank11_xanthate                  14956 non-null  float64
 44  rougher.output.concentrate_ag                       16778 non-null  float64
 45  rougher.output.concentrate_pb                       16778 non-null  float64
 46  rougher.output.concentrate_sol                      16698 non-null  float64
 47  rougher.output.concentrate_au                       16778 non-null  float64
 48  rougher.output.recovery                             14287 non-null  float64
 49  rougher.output.tail_ag                              14610 non-null  float64
 50  rougher.output.tail_pb                              16778 non-null  float64
 51  rougher.output.tail_sol                             14611 non-null  float64
 52  rougher.output.tail_au                              14611 non-null  float64
 53  rougher.state.floatbank10_a_air                     16807 non-null  float64
 54  rougher.state.floatbank10_a_level                   16807 non-null  float64
 55  rougher.state.floatbank10_b_air                     16807 non-null  float64
 56  rougher.state.floatbank10_b_level                   16807 non-null  float64
 57  rougher.state.floatbank10_c_air                     16807 non-null  float64
 58  rougher.state.floatbank10_c_level                   16814 non-null  float64
 59  rougher.state.floatbank10_d_air                     16802 non-null  float64
 60  rougher.state.floatbank10_d_level                   16809 non-null  float64
 61  rougher.state.floatbank10_e_air                     16257 non-null  float64
 62  rougher.state.floatbank10_e_level                   16809 non-null  float64
 63  rougher.state.floatbank10_f_air                     16802 non-null  float64
 64  rougher.state.floatbank10_f_level                   16802 non-null  float64
 65  secondary_cleaner.output.tail_ag                    16776 non-null  float64
 66  secondary_cleaner.output.tail_pb                    16764 non-null  float64
 67  secondary_cleaner.output.tail_sol                   14874 non-null  float64
 68  secondary_cleaner.output.tail_au                    16778 non-null  float64
 69  secondary_cleaner.state.floatbank2_a_air            16497 non-null  float64
 70  secondary_cleaner.state.floatbank2_a_level          16751 non-null  float64
 71  secondary_cleaner.state.floatbank2_b_air            16705 non-null  float64
 72  secondary_cleaner.state.floatbank2_b_level          16748 non-null  float64
 73  secondary_cleaner.state.floatbank3_a_air            16763 non-null  float64
 74  secondary_cleaner.state.floatbank3_a_level          16747 non-null  float64
 75  secondary_cleaner.state.floatbank3_b_air            16752 non-null  float64
 76  secondary_cleaner.state.floatbank3_b_level          16750 non-null  float64
 77  secondary_cleaner.state.floatbank4_a_air            16731 non-null  float64
 78  secondary_cleaner.state.floatbank4_a_level          16747 non-null  float64
 79  secondary_cleaner.state.floatbank4_b_air            16768 non-null  float64
 80  secondary_cleaner.state.floatbank4_b_level          16767 non-null  float64
 81  secondary_cleaner.state.floatbank5_a_air            16775 non-null  float64
 82  secondary_cleaner.state.floatbank5_a_level          16775 non-null  float64
 83  secondary_cleaner.state.floatbank5_b_air            16775 non-null  float64
 84  secondary_cleaner.state.floatbank5_b_level          16776 non-null  float64
 85  secondary_cleaner.state.floatbank6_a_air            16757 non-null  float64
 86  secondary_cleaner.state.floatbank6_a_level          16775 non-null  float64
dtypes: float64(86), object(1)
memory usage: 11.2+ MB
None

test_df info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5856 entries, 0 to 5855
Data columns (total 53 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date                                        5856 non-null   object
 1   primary_cleaner.input.sulfate               5554 non-null   float64
 2   primary_cleaner.input.depressant            5572 non-null   float64
 3   primary_cleaner.input.feed_size             5856 non-null   float64
 4   primary_cleaner.input.xanthate              5690 non-null   float64
 5   primary_cleaner.state.floatbank8_a_air      5840 non-null   float64
 6   primary_cleaner.state.floatbank8_a_level    5840 non-null   float64
 7   primary_cleaner.state.floatbank8_b_air      5840 non-null   float64
 8   primary_cleaner.state.floatbank8_b_level    5840 non-null   float64
 9   primary_cleaner.state.floatbank8_c_air      5840 non-null   float64
 10  primary_cleaner.state.floatbank8_c_level    5840 non-null   float64
 11  primary_cleaner.state.floatbank8_d_air      5840 non-null   float64
 12  primary_cleaner.state.floatbank8_d_level    5840 non-null   float64
 13  rougher.input.feed_ag                       5840 non-null   float64
 14  rougher.input.feed_pb                       5840 non-null   float64
 15  rougher.input.feed_rate                     5816 non-null   float64
 16  rougher.input.feed_size                     5834 non-null   float64
 17  rougher.input.feed_sol                      5789 non-null   float64
 18  rougher.input.feed_au                       5840 non-null   float64
 19  rougher.input.floatbank10_sulfate           5599 non-null   float64
 20  rougher.input.floatbank10_xanthate          5733 non-null   float64
 21  rougher.input.floatbank11_sulfate           5801 non-null   float64
 22  rougher.input.floatbank11_xanthate          5503 non-null   float64
 23  rougher.state.floatbank10_a_air             5839 non-null   float64
 24  rougher.state.floatbank10_a_level           5840 non-null   float64
 25  rougher.state.floatbank10_b_air             5839 non-null   float64
 26  rougher.state.floatbank10_b_level           5840 non-null   float64
 27  rougher.state.floatbank10_c_air             5839 non-null   float64
 28  rougher.state.floatbank10_c_level           5840 non-null   float64
 29  rougher.state.floatbank10_d_air             5839 non-null   float64
 30  rougher.state.floatbank10_d_level           5840 non-null   float64
 31  rougher.state.floatbank10_e_air             5839 non-null   float64
 32  rougher.state.floatbank10_e_level           5840 non-null   float64
 33  rougher.state.floatbank10_f_air             5839 non-null   float64
 34  rougher.state.floatbank10_f_level           5840 non-null   float64
 35  secondary_cleaner.state.floatbank2_a_air    5836 non-null   float64
 36  secondary_cleaner.state.floatbank2_a_level  5840 non-null   float64
 37  secondary_cleaner.state.floatbank2_b_air    5833 non-null   float64
 38  secondary_cleaner.state.floatbank2_b_level  5840 non-null   float64
 39  secondary_cleaner.state.floatbank3_a_air    5822 non-null   float64
 40  secondary_cleaner.state.floatbank3_a_level  5840 non-null   float64
 41  secondary_cleaner.state.floatbank3_b_air    5840 non-null   float64
 42  secondary_cleaner.state.floatbank3_b_level  5840 non-null   float64
 43  secondary_cleaner.state.floatbank4_a_air    5840 non-null   float64
 44  secondary_cleaner.state.floatbank4_a_level  5840 non-null   float64
 45  secondary_cleaner.state.floatbank4_b_air    5840 non-null   float64
 46  secondary_cleaner.state.floatbank4_b_level  5840 non-null   float64
 47  secondary_cleaner.state.floatbank5_a_air    5840 non-null   float64
 48  secondary_cleaner.state.floatbank5_a_level  5840 non-null   float64
 49  secondary_cleaner.state.floatbank5_b_air    5840 non-null   float64
 50  secondary_cleaner.state.floatbank5_b_level  5840 non-null   float64
 51  secondary_cleaner.state.floatbank6_a_air    5840 non-null   float64
 52  secondary_cleaner.state.floatbank6_a_level  5840 non-null   float64
dtypes: float64(52), object(1)
memory usage: 2.4+ MB
None

It looks like the first issue in our DataFrames are that the date column is object dtype when it should be converted to datetime. I'll go ahead and do that since it's will be easier to use the pandas library on it.

In [20]:
#Convert date column to datetime dtype

print('full_df head')
full_df['date'] = pd.to_datetime(full_df['date'])
print(full_df['date'].head())
print()

print('train_df head')
train_df['date'] = pd.to_datetime(train_df['date'])
print(train_df['date'].head())
print()

print('test_df head')
test_df['date'] = pd.to_datetime(test_df['date'])
print(test_df['date'].head())
print()

full_df head
0   2016-01-15 00:00:00
1   2016-01-15 01:00:00
2   2016-01-15 02:00:00
3   2016-01-15 03:00:00
4   2016-01-15 04:00:00
Name: date, dtype: datetime64[ns]

train_df head
0   2016-01-15 00:00:00
1   2016-01-15 01:00:00
2   2016-01-15 02:00:00
3   2016-01-15 03:00:00
4   2016-01-15 04:00:00
Name: date, dtype: datetime64[ns]

test_df head
0   2016-09-01 00:59:59
1   2016-09-01 01:59:59
2   2016-09-01 02:59:59
3   2016-09-01 03:59:59
4   2016-09-01 04:59:59
Name: date, dtype: datetime64[ns]

The date column has been updated appropriately to datetime format. The numeric columns are in float64, which is good since there are numerous decimal places to be compensated for to get the most accurate calculations. Next, it will be important to understand the column names better. **full_df** and **train_df** both have 87 columns, while **test_df** has 53.

#### 1.2 Check that recovery is calculated correctly. Using the training set, calculate recovery for the rougher.output.recovery feature. Find the MAE between your calculations and the feature values. Provide findings.

#### 1.3. Analyze the features not available in the test set. What are these parameters? What is their type?

#### 1.4. Perform data preprocessing.

### 2. Analyze the Data

#### 2.1. Take note of how the concentrations of metals (Au, Ag, Pb) change depending on the purification stage.

#### 2.2. Compare the feed particle size distributions in the training set and in the test set. If the distributions vary significantly, the model evaluation will be incorrect.

#### 2.3. Consider the total concentrations of all substances at different stages: raw feed, rougher concentrate, and final concentrate. Do you notice any abnormal values in the total distribution? If you do, is it worth removing such values from both samples? Describe the findings and eliminate anomalies.

### 3. Build the Model

#### 3.1. Write a function to calculate the final sMAPE value.

#### 3.2. Train different models. Evaluate them using cross-validation. Pick the best model and test it using the test sample. Provide findings.

Use these formulae for evaluation metrics:

In [23]:
#URLs for evaluation metric formula images
smape_url = "https://raw.githubusercontent.com/DHE42/sprint_10_repository/89e3644270ee88604f5d53b8935bfd0a777352cd/Image.png"
final_smape_url = "https://raw.githubusercontent.com/DHE42/sprint_10_repository/89e3644270ee88604f5d53b8935bfd0a777352cd/Image%201.png"

In [24]:
#Display url_1
display(Image(url=smape_url))
print()

In [25]:
#Display url_2
display(Image(url=final_smape_url))
print()

### 4. Self Evaluation Before Submission

Answer each of the questions below to check your reasoning so you can ensure this project is the best you can produce.

#### 4.1 Have you prepared and analyzed the data properly?

#### 4.2 What models have you developed?

#### 4.3 How did you check the model‘s quality?

#### 4.4 Have you followed all the steps of the instructions?

#### 4.5 Did you keep to the project structure and explain the steps performed?

#### 4.6 What are your findings?

#### 4.7 Have you kept the code neat and avoided code duplication?

### 5. Conclusion

Write your conclusion based upon the self evaluation.